name: Build

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           gcc-aarch64-linux-gnu iasl mtools subversion \
                           lzma-dev uuid-dev

      - name: Sources (git)
        run: |
          make submodules

      - name: Sources (subversion)
        run: |
          make firmware

      - name: Build (EFI)
        run: |
          make efi

      - name: Build (iPXE)
        run: |
          make ipxe -j 4

      - name: Construct
        run: |
          make

      - name: Create release
        id: create_release
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload (pipxe4.img)
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: pipxe4.img
          asset_path: pipxe4.img
          asset_content_type: application/octet-stream

      - name: Upload (pipxe4.zip)
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: pipxe4.zip
          asset_path: pipxe4.zip
          asset_content_type: application/zip
